@startuml

skin rose

interface Indicavel {
  -Boolean isElegivel();
  -void setNumeroDeIndicacoes();
}

class Filme <<Component>> implements Indicavel {
  -String nome;
  -String genero;
  +Boolean elegivel;
  +Short numeroDeIndicacoes;
}

class Ator <<Component>> implements Indicavel {
  -String nome;
  -String nacionalidade;
  -Boolean elegivel;
  -Short numeroDeIndicacoes;
}

class Indicacao <<Component>> {
  -Indicavel indicavel;
  -String categoria;
}

class OscarService <<Service>> {
  -ArrayList<Indicacao> indicacoes;
  +void adicionarIndicacao(Indicacao indicacao)
  +void mostrarListaIndicados()
}

@enduml