stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: maven:3.8.3-openjdk-17
  script:
    - mvn clean test
  only:
    - develop
    - master

build:
  stage: build
  image: maven:3.8.3-openjdk-17
  script:
    - mvn clean package -DskipTests
  artifacts:
    name: app.jar
    paths:
      - ./target/*.jar
    when: always
    expire_in: 1 hrs
  only:
    - develop
    - master

deploy-gitlab:
  image: docker
  stage: deploy
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  dependencies:
    - build
  only:
    - master

deploy-gcloud:
  image: google/cloud-sdk:alpine
  stage: deploy
  script:
    - echo $SERVICE_ACCOUNT_KEY > service-account-key.json
    - gcloud auth activate-service-account --key-file service-account-key.json
    - gcloud config set project $PROJECT_ID 
    - gcloud auth configure-docker
    - gcloud builds submit --tag gcr.io/$PROJECT_ID/$SERVICE_ID
    - gcloud run deploy $SERVICE_ID --image gcr.io/$PROJECT_ID/$SERVICE_ID --region=us-central1 --platform managed --allow-unauthenticated
  dependencies:
    - build
  when: manual
  only:
    - master